### ISSUE TITLE
[Feature Request] Add custom noteid when embedding nocomment so that comments show up under custom note

### ISSUE THREAD

**Issue by InnocuousFinch** [fiatjaf/nocomment#11]
Use case: I want to make a post on Nostr showing off the new guide I just wrote, which has nocomment embedded added to the bottom of it: https://sovrnbitcoiner.com/receiving-self-sovereign-zaps/

It would be cool if the comments from nocomment would display replies directly under the post I make to share the guide. And that comments made to my post would show up under the nocomment embed on the guide.

**Comment by fiatjaf** [comment]
Here it is: https://github.com/fiatjaf/nocomment/commit/d72f36b93dbb2dfed460d26a6ddfc633717f3a62

Not tested.
If it's broken please fix it for me.

**Comment by BitcoinQnA** [comment]
I think this change borked the whole thing @fiatjaf. 

I've checked the 3 instances I know running this (including [your site](http://fiatjaf.com/nostr.html) and none are working. 

I'd love to have the knowledge to be able to fix, but I do not. So bringing it to your attention is the most I can do currently.

**Comment by fiatjaf** [comment]
I think it is fixed now.
