### ISSUE TITLE
I think get key button is confusing to normal users

### ISSUE THREAD

**Issue by bitcoinuser** [fiatjaf/nocomment#13]
Hi,

I think get key button is confusing to normal users. In my opinion should work this way:

1- Have a button called comment
2- When the user click on comment button, open the field to write the comment and a new button called post.

**Comment by fiatjaf** [comment]
I agree. Can you open a pull request?

**Comment by verityj** [comment]
I agree. And I just discovered your extension, thanks @fiatjaf ! Created the pull request https://github.com/fiatjaf/nocomment/pull/20
