### ISSUE TITLE
add relay wss://relay.mostr.pub

### ISSUE THREAD

**Issue by rocky-III** [fiatjaf/nocomment#18]
could you add the relay wss://relay.mostr.pub to the created nostr account  on snort.social so that the comments could also be followed by AP accounts ?  - THANKS

https://soapbox.pub/blog/mostr-fediverse-nostr-bridge/

**Comment by fiatjaf** [comment]
This is not how it is supposed to work.

**Comment by rocky-III** [comment]
@fiatjaf could you please explain what you mean by that. 

you don' t like the AP bridge?

**Comment by fiatjaf** [comment]
No, we just need something to allow users of this comment widget to pick the relays they want.

Also, on the Mostr side, it should be able to connect to external relays and push their stuff into AP.
