### ISSUE TITLE
Plugin not picking up all comments when there are multiple comments rather than only one

### ISSUE THREAD

**Issue by nima1981** [fiatjaf/nocomment#26]
Loving this plugin's look and feel! It works sporadically but for many posts on my site with multiple comments no comments show up at all, even though every relay that the comments were posted on are included in the relay list.

For example:

https://dissentwatch.com/boost/?boost_post_id=524256

As you can see at https://nostr.band/note1v3qgcmthrch5uk3f4dstp9sd4uttpx5a4yva72xmqppap56lh2gs7mjv5f there are 6 relays listed:
wss://relay.shitforce.one/
wss://nostr.anchel.nl/
wss://nostramsterdam.vpx.moe/
wss://relay.wellorder.net/
wss://nostr-pub.wellorder.net/
wss://n.xmr.se/

I've included all of these relays in the nocomment script, but no comments are showing up at all.

There are several other examples like this on my site: https://dissentwatch.com/trending/?trending_order=comments

There are also some where the comments do show up just fine, they all have a single comment rather than multiple (not sure if that's why?):

https://dissentwatch.com/boost/?boost_post_id=666775
https://dissentwatch.com/boost/?boost_post_id=666744
https://dissentwatch.com/boost/?boost_post_id=666965

**Comment by fiatjaf** [comment]
Thank you very much for this issue. The issue should be fixed. Please let me know if not.

**Comment by nima1981** [comment]
Works like a charm now, thanks very much, this is a great addition to my site!! :D
