### ISSUE TITLE
Login with existing nostr account

### ISSUE THREAD

**Issue by nima1981** [fiatjaf/nocomment#27]
Is it possible to login with my existing nostr account before posting a comment?

**Comment by fiatjaf** [comment]
Yes, if you have a NIP-07 extension it should prompt you to get your pubkey when you click to comment.

**Comment by nima1981** [comment]
OK, for example, I have the nos2x-fox extension installed in my firefox. I went to https://dissentwatch.com/boost/?boost_post_id=668155 entered a comment and published it. It published it with a new random public key and didn't prompt me for anything it seems.

**Comment by fiatjaf** [comment]
I just checked the code and I still think it should be working.
Can you try from another browser installation, incognito mode or another extension?

**Comment by nima1981** [comment]
Yes, I tried from both regular and private browsing mode, will try other things.

**Comment by nima1981** [comment]
I think my nos2x extension was old an defective. I reinstalled it and now it worked! :D
