### ISSUE TITLE
React component attributes

### ISSUE THREAD

**Issue by nima1981** [fiatjaf/nocomment#28]
In the readme the only parameter mentioned for the react component is the relays. Are the other ones, such as the event ID, the post owner etc. also available in the react component?

**Comment by fiatjaf** [comment]
Yes, they are all available.
Here's how the non-React thing invokes React: https://github.com/fiatjaf/nocomment/blob/3397d29514a35343c130118270dfb2087becb158/embeddable/embed.jsx#L20-L25

**Comment by nima1981** [comment]
Perfect, thanks!
