### ISSUE TITLE
Scripts with frameworks 

### ISSUE THREAD

**Issue by Nisar-safi** [fiatjaf/nocomment#45]
The plugin or script you provided, I tested it in Svelte as well as in React, and it's not working at all. The comment box is not showing up as you claimed it would for use on any website. I tried using it in Svelte and React, but the script is completely unusable. What is the solution for this? Do you have any idea about it?

**Comment by fiatjaf** [comment]
No.

**Comment by Nisar-safi** [comment]
Alright, if we can't use the script or plugin, or if you have no idea how to use it (as I checked), it's fine. But the component you made for React, which is currently working in React, is there any way to integrate it into Svelte or SvelteKit or another similar framework? Because the package you provided is only for React. So, is there any chance or way we can take that same component and integrate it into Svelte?

**Comment by fiatjaf** [comment]
I don't have a way to fix your problem. Eventually I'll release a component that supersedes this one, and maybe that will work on Svelte.

Meanwhile you can use https://github.com/franzaps/zapthreads
